name: Use github actions to test execution

on: [push]

jobs:
  build:
    name: test poc
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        
    steps:

      - name: checkout repo for testing
        uses: actions/checkout@v1

      - name: Test flight search on chrome
        uses: DevExpress/testcafe-action@latest
        with:
          args: "chrome:headless tests/findflightstest.js"

      - name: Test flight search on firefox
        uses: DevExpress/testcafe-action@latest
        with:
          args: "firefox:headless tests/findflightstest.js"